name: Update F-Droid repository

on:
  push:
    branches: [main]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Update F-Droid repository
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
        
      - name: Create directory structure
        run: mkdir -p fdroid/repo
        
      - name: Restore mtime
        run: |
          sudo apt install git-restore-mtime 
          git restore-mtime
    
      - name: Install F-Droid server
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get install fdroidserver
          
      - name: Setup up keystore
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "keystorepass: ${{ secrets.KEYSTORE_PASS }}" >> fdroid/config.yml
          echo "keypass: ${{ secrets.KEY_PASS }}" >> fdroid/config.yml
          
      - name: Change permission for sensitive files
        run: |
          chmod 0600 fdroid/config.yml
          chmod 0600 fdroid/keystore.p12

      - name: Download releases
        run: ./download.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lint
        run: fdroid lint
        working-directory: ./fdroid
        
      - name: Run update
        run: fdroid update --create-metadata --pretty --rename-apks
        working-directory: ./fdroid
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Copy repo to public folder
        run: cp -rf fdroid/repo public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

